import logging

from app.schemas import NutritionPlan, RagHit, SupervisorDirectives, UserProfile
from app.services.llm import LlmClient
from app.services.rag import RagService

logger = logging.getLogger(__name__)


def create_nutrition_plan(
    profile: UserProfile,
    directives: SupervisorDirectives,
    rag: RagService,
    llm: LlmClient | None = None,
) -> NutritionPlan:
    hits = rag.recovery_meals(profile)
    base_calories = int((10 * profile.weight_kg + 6.25 * profile.height_cm - 5 * profile.age + 5) * 1.45)
    protein_g = int(profile.weight_kg * 1.8)

    if "lower activity" in directives.nutritionist_directive.lower():
        calorie_target = base_calories - 200
        title = "Recovery-focused nutrition day"
    elif profile.goal == "fat_loss":
        calorie_target = base_calories - 350
        title = "High-satiety fat-loss day"
    else:
        calorie_target = base_calories + 150
        title = "Training-support nutrition day"

    fallback = NutritionPlan(
        title=title,
        calorie_target=calorie_target,
        protein_g=protein_g,
        meals=_meals_from_rag(hits),
        notes=[
            "Keep hydration steady and add electrolytes if morning heart rate remains elevated.",
            "Respect dietary restrictions before final meal selection.",
            "Meal choices are grounded in the retrieved nutrition knowledge base.",
        ],
        rag_context=hits,
    )
    if llm is None or not llm.enabled:
        logger.info("Nutrition plan using deterministic fallback: LLM disabled.")
        return fallback

    logger.info("Nutrition plan requesting Gemini generation.")
    generated = llm.generate_structured(
        output_model=NutritionPlan,
        system_prompt=(
            "You are the Nutritionist Agent in a multi-agent fitness coaching board. "
            "Create practical nutrition plans grounded in retrieved recipe context. "
            "Respect dietary restrictions and do not provide medical treatment claims."
        ),
        user_prompt=(
            "Generate a nutrition plan as JSON.\n\n"
            f"User profile:\n{profile.model_dump_json()}\n\n"
            f"Supervisor directives:\n{directives.model_dump_json()}\n\n"
            f"Calculated targets:\ncalorie_target={calorie_target}, protein_g={protein_g}\n\n"
            f"Retrieved nutrition context:\n{_rag_context_json(hits)}\n\n"
            "Requirements:\n"
            "- Keep calorie_target within 150 kcal of the calculated target.\n"
            "- Keep protein_g within 15g of the calculated target.\n"
            "- Include 4 meals or meal slots.\n"
            "- Respect dietary restrictions.\n"
            "- Include 2 to 5 concise notes.\n"
            "- Omit rag_context or return it as an empty list; the API will attach retrieved context."
        ),
    )
    if generated is None:
        logger.info("Nutrition plan using deterministic fallback: Gemini generation failed.")
        return fallback
    if abs(generated.calorie_target - calorie_target) > 150:
        logger.info(
            "Nutrition plan using deterministic fallback: Gemini calorie target outside guardrail."
        )
        return fallback
    if abs(generated.protein_g - protein_g) > 15:
        logger.info("Nutrition plan using deterministic fallback: Gemini protein target outside guardrail.")
        return fallback

    logger.info("Nutrition plan generated by Gemini.")
    notes = list(generated.notes)
    if not any("Gemini" in note for note in notes):
        notes.append("Plan generated by Gemini using retrieved nutrition context.")
    return generated.model_copy(update={"rag_context": hits, "notes": notes})


def _meals_from_rag(hits: list[RagHit]) -> list[str]:
    if not hits:
        return [
            "Greek yogurt bowl with berries, oats, walnuts, and cinnamon",
            "Chicken or tofu grain bowl with leafy greens, olive oil, and legumes",
            "Salmon or lentil dinner with potatoes and roasted vegetables",
            "Optional snack: cottage cheese or hummus with vegetables",
        ]

    meals = [f"{hit.title} ({_macro_summary(hit.snippet)})" for hit in hits[:4]]
    if len(meals) < 4:
        meals.append("Optional snack: cottage cheese or hummus with vegetables")
    return meals


def _macro_summary(snippet: str) -> str:
    parts = []
    for marker in ["Protein", "Carbs", "Fat"]:
        start = snippet.find(f"{marker}:")
        if start == -1:
            continue
        end = snippet.find(".", start)
        if end == -1:
            end = len(snippet)
        parts.append(snippet[start:end].lower())

    return ", ".join(parts) if parts else "macro details from retrieved recipe"


def _rag_context_json(hits: list[RagHit]) -> str:
    return "[" + ", ".join(hit.model_dump_json() for hit in hits[:6]) + "]"
